### ISSUE TITLE
lookup-by-net not effective for pools with naive reverse DNS configuration

### ISSUE THREAD

**Issue by koniiiik** [schweikert/postgrey#32]
The check at https://github.com/schweikert/postgrey/blob/ed50f9f754919bf14619d15533356fc443f55672/postgrey#L190-L192 makes postgrey check individual host IP addresses for pools such as Facebook's, which use a naive reverse DNS setup with a separate IP-based domain name for every single member of a pool.

I don't know how effective that special case is, but perhaps it could be at least made optional?

**Comment by AGWA** [comment]
Amazon SES also uses reverse DNS that triggers this check (e.g. `a27-143.smtp-out.us-west-2.amazonses.com`) and sends retries from different IP addresses in the same `/24` pool.   I think this special case does more harm than good.

**Comment by jesboat** [comment]
I run a pretty small site (5 users) but I've seen a similar reverse DNS with Amazon, Verizon, Netflix, and Facebook in the last couple weeks. It seems like this might be a pretty common case for large sites (if you have a large pool, you might want separate reverse DNS for all outgoing IP, so that the forward(reverse(ip))==ip, and if your pool is large enough, why not include the IP in the name?)

In the case described in the comment in the code, where the subnet is an ISP, it seems unlikely to change anything at all.
